### ISSUE TITLE
Dose the project have a plan to support substrate 2.0

### ISSUE THREAD

**Issue by haoming06** [polkascan/polkascan-pre#5]

**Comment by emielvanderhoek** [comment]
Substrate 2.0 does not have a stable release yet, though Kusama and Edgeware and new networks can be considered to be built on Substrate 2.0. Since Polkascan currently supports these networks we effectively already support Substrate 2.0.

That said (and to manage expectations) our mid-term goals is a build a generalized Substrate explorer and multi-chain analytics and data exploration technologies.

Our short-term goals and priorities are with providing support for specific networks. We aim to support the public production networks first (such as Kusama) and we aim to provide support for public testnets next (examples can be found on https://polkascan.io).

We have a very small team and limited resources and thus we need to consider our priorities very carefully. That said, if you run into particular issues, please post an issue. Perhaps it is something that is trivial and can be easily resolved.
